# Generated by Django 4.2.7 on 2023-12-02 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the vendor', max_length=100)),
                ('contact_details', models.TextField(help_text='contact details of the vendor')),
                ('address', models.TextField(help_text='address of the vendor')),
                ('vendor_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique identifier for the vendor', unique=True)),
                ('on_time_delivery_rate', models.FloatField(blank=True, help_text='percentage of on time deliveries by the vendor')),
                ('quality_rating_avg', models.FloatField(blank=True, help_text='average quality rating based on purchase orders')),
                ('average_response_time', models.FloatField(blank=True, help_text='average time taken to respond to purchase orders')),
                ('fulfillment_rate', models.FloatField(blank=True, help_text='percentage of purchase orders fulfilled successfully')),
            ],
        ),
    ]
