# Generated by Django 4.2.7 on 2023-12-02 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, help_text='date when the order was acknowledged by the vendor', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 2, 24, 23, 39671), help_text='expected or actual delivery date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(blank=True, help_text='rating for the order', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='the date the performance was recorded')),
                ('on_time_delivery_rate', models.FloatField(help_text='on time delivery rate on the recorded date')),
                ('quality_rating_avg', models.FloatField(help_text='average rating of the vendor on the recorded date')),
                ('average_response_time', models.FloatField(help_text='average response time of the vendor on the recorded date')),
                ('fulfillment_rate', models.FloatField(help_text='fulfillment rate of the vendor on the recorded date')),
                ('vendor', models.ForeignKey(help_text='the vendor whose performance is being monitored', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
