# Generated by Django 4.2.7 on 2023-12-04 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.FloatField(editable=False, help_text='average response time of the vendor on the recorded date'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(editable=False, help_text='fulfillment rate of the vendor on the recorded date'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(editable=False, help_text='on time delivery rate on the recorded date'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.FloatField(editable=False, help_text='average rating of the vendor on the recorded date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 11, 59, 24, 4221), help_text='expected or actual delivery date'),
        ),
    ]
