# Generated by Django 4.2.7 on 2023-12-04 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 12, 48, 17, 984980), help_text='expected or actual delivery date'),
        ),
    ]
